name: OCA Quality Tools

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clone OCA maintainer-quality-tools
        run: git clone https://github.com/OCA/maintainer-quality-tools.git maintainer-quality-tools

      - name: Remove incompatible PyYAML from requirements
        run: sed -i '/pyyaml==5.4/d' maintainer-quality-tools/requirements.txt

      - name: Install requirements
        run: pip install -r maintainer-quality-tools/requirements.txt

      - name: Run pylint-odoo
        run: maintainer-quality-tools/run_pylint.sh .

      - name: Run flake8
        run: maintainer-quality-tools/run_flake8.sh .

      - name: Run black
        run: maintainer-quality-tools/run_black.sh .
