name: Odoo Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pylint-odoo, flake8, black
        run: |
          pip install pylint pylint-odoo flake8 black

      - name: Run pylint-odoo
        run: pylint --load-plugins=pylint_odoo .

     # - name: Run flake8
     #   run: flake8 .

      - name: Run black check
        run: black --check .
